import express from 'express';
import cors from 'cors';
import Stripe from 'stripe';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';

const app = express();
const PORT = process.env.PORT || 4000;
const stripe = new Stripe(process.env.STRIPE_SECRET_KEY || '');
const JWT_SECRET = process.env.JWT_SECRET || 'change-me';

app.use(cors());

app.post('/api/stripe/webhook', express.raw({ type: 'application/json' }), async (req, res) => {
  try { res.json({ received: true }); } catch (e) { res.status(500).json({ error: e.message }); }
});

app.use(express.json());

const db = { members: {}, byEmail: {} };
const states = ['AL Alabama','AK Alaska','AZ Arizona','AR Arkansas','CA California','CO Colorado','CT Connecticut','DE Delaware','FL Florida','GA Georgia','HI Hawaii','ID Idaho','IL Illinois','IN Indiana','IA Iowa','KS Kansas','KY Kentucky','LA Louisiana','ME Maine','MD Maryland','MA Massachusetts','MI Michigan','MN Minnesota','MS Mississippi','MO Missouri','MT Montana','NE Nebraska','NV Nevada','NH New Hampshire','NJ New Jersey','NM New Mexico','NY New York','NC North Carolina','ND North Dakota','OH Ohio','OK Oklahoma','OR Oregon','PA Pennsylvania','RI Rhode Island','SC South Carolina','SD South Dakota','TN Tennessee','TX Texas','UT Utah','VT Vermont','VA Virginia','WA Washington','WV West Virginia','WI Wisconsin','WY Wyoming'].map(s=>{const [abbr,...rest]=s.split(' ');return {abbr,name:rest.join(' ')}});

function norm(email){return String(email||'').trim().toLowerCase();}
function id(){return 'mem_'+Math.random().toString(36).slice(2)+Date.now().toString(36)}
function token(m){return jwt.sign({id:m.id,email:m.email},JWT_SECRET,{expiresIn:'30d'});}
function auth(req,res,next){try{const h=req.headers.authorization||'';const t=h.startsWith('Bearer ')?h.slice(7):'';const d=jwt.verify(t,JWT_SECRET);const m=db.members[d.id];if(!m)return res.status(401).json({error:'Member not found'});req.member=m;next();}catch(e){res.status(401).json({error:'Invalid token'});}}
function isActive(s){return s==='active'||s==='trialing';}
function label(s){return s==='active'?'Active Protection Member':s==='trialing'?'Trialing Protection Member':s==='past_due'?'Past Due — Payment Issue':s==='canceled'?'Canceled':s==='unpaid'?'Unpaid — Access Restricted':s==='not_found'?'No Active Membership Found':'Membership Status Unknown'}
function permitStatus(p){if(!p||!p.expirationDate)return {status:'missing',label:'Permit Info Needed',message:'Add your permit state, issue date, and expiration date.'};const exp=new Date(p.expirationDate+'T00:00:00');const days=Math.ceil((exp-new Date())/86400000);if(days<0)return {status:'expired',label:'Expired',message:'Your permit appears expired.',daysRemaining:days};if(days<=183)return {status:'renewal_window',label:'Renewal Window',message:'Your permit is within the 6-month renewal window.',daysRemaining:days};return {status:'active',label:'Active',message:'Your permit appears active.',daysRemaining:days};}
function pub(m){return {id:m.id,email:m.email,name:m.name,membershipStatus:m.membershipStatus,membershipLabel:label(m.membershipStatus),accessAllowed:isActive(m.membershipStatus),permitProfile:m.permitProfile,permitStatus:permitStatus(m.permitProfile),lastCheckedAt:m.lastCheckedAt};}
async function stripeStatus(email){const customers=await stripe.customers.list({email:norm(email),limit:10});if(!customers.data.length)return 'not_found';const cust=customers.data.sort((a,b)=>b.created-a.created)[0];const subs=await stripe.subscriptions.list({customer:cust.id,status:'all',limit:10});if(!subs.data.length)return 'not_found';const priority=['active','trialing','past_due','unpaid','incomplete','canceled'];subs.data.sort((a,b)=>(priority.indexOf(a.status)<0?99:priority.indexOf(a.status))-(priority.indexOf(b.status)<0?99:priority.indexOf(b.status)));return subs.data[0].status;}

app.post('/api/auth/register', async (req,res)=>{try{const email=norm(req.body.email);const password=String(req.body.password||'');if(!email||!password)return res.status(400).json({error:'Email and password are required'});if(db.byEmail[email])return res.status(409).json({error:'An account already exists for this email'});const m={id:id(),email,name:req.body.name||'Prime Defense Member',passwordHash:await bcrypt.hash(password,10),membershipStatus:await stripeStatus(email),permitProfile:{permitState:'MI',issueDate:'',expirationDate:''},lastCheckedAt:new Date().toISOString()};db.members[m.id]=m;db.byEmail[email]=m.id;res.json({token:token(m),member:pub(m)});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/auth/login', async (req,res)=>{try{const email=norm(req.body.email);const m=db.members[db.byEmail[email]];if(!m||!(await bcrypt.compare(String(req.body.password||''),m.passwordHash)))return res.status(401).json({error:'Invalid email or password'});m.membershipStatus=await stripeStatus(email);m.lastCheckedAt=new Date().toISOString();res.json({token:token(m),member:pub(m)});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/member/me',auth,(req,res)=>res.json({member:pub(req.member)}));
app.post('/api/member/refresh-stripe-status',auth,async(req,res)=>{req.member.membershipStatus=await stripeStatus(req.member.email);req.member.lastCheckedAt=new Date().toISOString();res.json({member:pub(req.member)});});
app.put('/api/member/permit',auth,(req,res)=>{req.member.permitProfile={permitState:req.body.permitState||'MI',issueDate:req.body.issueDate||'',expirationDate:req.body.expirationDate||''};res.json({member:pub(req.member),permitStatus:permitStatus(req.member.permitProfile)});});
app.post('/api/member/billing-portal',auth,async(req,res)=>res.status(501).json({error:'Billing portal setup pending'}));
app.get('/api/states',auth,(req,res)=>{if(!isActive(req.member.membershipStatus))return res.status(403).json({error:'Active membership required'});res.json(states);});
app.get('/api/states/:abbr',auth,(req,res)=>{const st=states.find(x=>x.abbr===String(req.params.abbr).toUpperCase());if(!st)return res.status(404).json({error:'State not found'});res.json({abbr:st.abbr,name:st.name,status:'Functioning Mock Data',syncStatus:'mock',lastSynced:'Mock data',categories:{reciprocity:{answer:`${st.name} reciprocity field populated`,details:'Shows whether a Michigan CPL is recognized.',sourceName:'Mock official source'},dutyToInform:{answer:`${st.name} duty-to-inform field populated`,details:'Explains law enforcement notification expectations.',sourceName:'Mock official source'},vehicleCarry:{answer:`${st.name} vehicle carry guidance populated`,details:'Summarizes vehicle carry considerations.',sourceName:'Mock official source'},restrictedLocations:{answer:`${st.name} restricted locations populated`,details:'Lists major restricted places.',sourceName:'Mock official source'},signsEnforceable:{answer:`${st.name} signs enforceable field populated`,details:'Explains whether no-firearms signs have legal force.',sourceName:'Mock official source'},openCarry:{answer:`${st.name} open carry field populated`,details:'Shows open carry status and limitations.',sourceName:'Mock official source'},constitutionalCarry:{answer:`${st.name} constitutional carry field populated`,details:'Shows permitless carry status.',sourceName:'Mock official source'},useOfForce:{answer:'High-level awareness only',details:'Not legal advice.',sourceName:'Mock official source'},lawEnforcementInteraction:{answer:`${st.name} police-interaction guidance populated`,details:'Highlights practical differences.',sourceName:'Mock official source'},differentFromMichigan:{answer:`${st.name} vs. Michigan comparison populated`,details:'Quick travel comparison.',sourceName:'Mock official source'}}});});

const html = `<!doctype html><html><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>Prime Defense Protection Member</title><style>
body{margin:0;background:radial-gradient(circle at top left,#3a0b0f,#111 34%,#050505);color:#fff;font-family:Arial,sans-serif}.shell{max-width:1100px;margin:auto;padding:22px}.panel,.hero{background:rgba(16,16,16,.96);border:1px solid rgba(255,255,255,.09);padding:24px;border-radius:24px;margin:18px 0;box-shadow:0 18px 50px rgba(0,0,0,.35)}.hero{background:linear-gradient(135deg,rgba(26,26,26,.98),rgba(8,8,8,.98));border-radius:28px}.brand{color:#ef233c;font-weight:900;letter-spacing:3px;font-size:12px}.title{font-size:clamp(36px,7vw,64px);line-height:.9;margin:10px 0}.text{color:#cfcfcf;line-height:1.55}.btn{border:0;border-radius:16px;background:#ef233c;color:#fff;padding:16px 20px;font-weight:900;cursor:pointer;margin:6px}.btn.dark{background:#161616;border:1px solid rgba(255,255,255,.16)}input,select{width:100%;box-sizing:border-box;padding:15px;border-radius:16px;border:1px solid rgba(255,255,255,.14);background:#080808;color:#fff;font-size:16px;margin:8px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px}.card{background:rgba(0,0,0,.28);border:1px solid rgba(255,255,255,.08);border-radius:18px;padding:16px}.badge{display:inline-block;background:rgba(34,197,94,.13);border:1px solid rgba(34,197,94,.35);color:#8cffb0;border-radius:999px;padding:10px 14px;font-weight:900}.warn{background:rgba(245,158,11,.12);border:1px solid rgba(245,158,11,.25);border-radius:18px;padding:16px;color:#ffe7b3;margin:12px 0}.script{font-size:clamp(24px,5vw,38px);line-height:1.15;font-weight:900;margin:12px 0}.state{border:1px solid rgba(255,255,255,.12);border-radius:14px;background:#090909;color:#fff;padding:14px 10px;font-weight:900;cursor:pointer}.row{display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap}.success{background:rgba(34,197,94,.12);border:1px solid rgba(34,197,94,.25);border-radius:18px;padding:16px;color:#8cffb0}.source{margin-top:12px;padding-top:10px;border-top:1px solid rgba(255,255,255,.08);color:#9ca3af;font-size:12px}
</style></head><body><div id="app"></div><script>
const API=''; let token=localStorage.getItem('pd_token')||''; let member=null; let states=[]; let contact={name:'',phone:''}; const USCCA_PHONE='8776771919', USCCA_DISPLAY='877-677-1919';
const app=document.getElementById('app'); function el(h){app.innerHTML=h} async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d}
async function boot(){if(token){try{member=(await api('/api/member/me')).member; if(member.accessAllowed) states=await api('/api/states'); renderHome();}catch(e){token='';localStorage.removeItem('pd_token');renderAuth(e.message)}}else renderAuth()}
function renderAuth(msg=''){el('<div class="shell"><div class="brand">PRIME DEFENSE TRAINING</div><h1 class="title">Member Login</h1><p class="text">Use the same email used for your PDPP / Stripe membership.</p><section class="panel"><input id="name" placeholder="Name (register only)"><input id="email" type="email" placeholder="Membership email"><input id="pw" type="password" placeholder="Password">'+(msg?'<div class="warn">'+msg+'</div>':'')+'<button class="btn" onclick="auth(\'login\')">Login</button><button class="btn dark" onclick="auth(\'register\')">Register</button></section></div>')}
async function auth(mode){try{const body={name:document.getElementById('name').value,email:document.getElementById('email').value,password:document.getElementById('pw').value};const d=await api('/api/auth/'+mode,{method:'POST',body:JSON.stringify(body)});token=d.token;localStorage.setItem('pd_token',token);member=d.member;if(member.accessAllowed)states=await api('/api/states');renderHome();}catch(e){renderAuth(e.message)}}
function logout(){localStorage.removeItem('pd_token');token='';member=null;renderAuth()}
function renderHome(){if(!member.accessAllowed)return renderLocked(); el('<div class="shell"><section class="hero"><div class="row"><div><div class="brand">PRIME DEFENSE TRAINING</div><h1 class="title">Prime Defense Protection Member</h1><p class="text">Premium member-only dashboard connected to Stripe membership status.</p></div><div class="badge">'+member.membershipLabel+'</div></div><button class="btn" onclick="renderEmergency(\'shooting\')">Emergency Mode: Shooting</button><button class="btn" onclick="renderEmergency(\'no-shots\')">Emergency Mode: No Shots Fired</button><button class="btn dark" onclick="renderAftermath()">Aftermath Mode</button></section><section class="panel"><div class="brand">MEMBERSHIP STATUS</div><h2>'+member.membershipLabel+'</h2><p class="text">Signed in as '+member.email+'</p><button class="btn dark" onclick="refresh()">Refresh Status</button><button class="btn dark" onclick="logout()">Logout</button></section>'+permitSection()+'<section class="panel"><div class="brand">RECIPROCITY GUIDE</div><h2>State-by-State Carry Guide</h2><div class="grid">'+states.map(s=>'<button class="state" onclick="openState(\''+s.abbr+'\')">'+s.abbr+'</button>').join('')+'</div></section><section class="panel"><div class="brand">EMERGENCY CONTACT</div><h2>Family / Trusted Contact</h2><input id="cname" placeholder="Contact name" value="'+(contact.name||'')+'"><input id="cphone" placeholder="Phone number" value="'+(contact.phone||'')+'"><button class="btn dark" onclick="saveContact()">Save Contact</button></section></div>')}
function permitSection(){const p=member.permitProfile||{}, st=member.permitStatus||{};return '<section class="panel"><div class="row"><div><div class="brand">MY PERMIT</div><h2>Permit Profile</h2><p class="text">Save your permit state, issue date, and expiration date.</p></div><div class="badge">'+(st.label||'Permit Info Needed')+'</div></div><div class="grid"><label>Permit State<select id="permitState"><option value="MI">Michigan</option><option value="OH">Ohio</option><option value="IN">Indiana</option><option value="FL">Florida</option></select></label><label>Issue Date<input id="issueDate" type="date" value="'+(p.issueDate||'')+'"></label><label>Expiration Date<input id="expirationDate" type="date" value="'+(p.expirationDate||'')+'"></label></div><button class="btn" onclick="savePermit()">Save Permit</button><p class="text">'+(st.message||'Add permit details to calculate status.')+'</p></section>'}
function saveContact(){contact={name:document.getElementById('cname').value,phone:document.getElementById('cphone').value};renderHome()}
async function savePermit(){try{const body={permitState:document.getElementById('permitState').value,issueDate:document.getElementById('issueDate').value,expirationDate:document.getElementById('expirationDate').value};const d=await api('/api/member/permit',{method:'PUT',body:JSON.stringify(body)});member=d.member;renderHome();}catch(e){alert(e.message)}}
async function refresh(){try{member=(await api('/api/member/refresh-stripe-status',{method:'POST'})).member;if(member.accessAllowed)states=await api('/api/states');renderHome()}catch(e){alert(e.message)}}
function renderLocked(){el('<div class="shell"><div class="brand">MEMBERSHIP REQUIRED</div><h1 class="title">Access Locked</h1><section class="panel"><h2>'+member.membershipLabel+'</h2><p class="text">Signed in as '+member.email+'</p><button class="btn" onclick="refresh()">Refresh Membership Status</button><button class="btn dark" onclick="logout()">Logout</button></section></div>')}
async function openState(abbr){try{const d=await api('/api/states/'+abbr);el('<div class="shell"><button class="btn dark" onclick="renderHome()">Back</button><div class="brand">RECIPROCITY GUIDE</div><h1 class="title">'+d.name+'</h1><section class="panel"><div class="brand">STATUS</div><h2>'+d.status+'</h2><p class="text">Sync status: '+d.syncStatus+'</p></section><div class="grid">'+Object.entries(d.categories).map(([k,v])=>'<div class="card"><div class="brand">'+k.replace(/([A-Z])/g,' $1').toUpperCase()+'</div><h3>'+v.answer+'</h3><p class="text">'+v.details+'</p><div class="source">Source: '+(v.sourceName||'pending')+'</div></div>').join('')+'</div><div class="warn">Educational information only. Not legal advice.</div></div>')}catch(e){alert(e.message)}}
function renderEmergency(mode){const shoot=mode==='shooting'; let html='<div class="shell"><button class="btn dark" onclick="renderHome()">Exit</button><div class="brand">PRIME DEFENSE PROTECTION MEMBER</div><h1 class="title">Emergency Mode</h1><section class="panel"><div class="brand">STEP 1 — CALL 911</div>'; if(shoot){html+='<div class="script">“I was attacked, feared for my life, and had to defend myself. Please send both police and an ambulance to this location.”</div><div class="warn">Secondary: “There has been a self-defense shooting at this location. Send help.”</div>'}else{html+='<div class="script">“My name is [name], and I need to report an attack or possible attack at this location.”</div><div class="warn">“I have a permit to carry and exposed my firearm, but no shots were fired.”</div>'} html+='<button class="btn" onclick="location.href=\'tel:911\'">CALL 911</button></section><section class="panel"><div class="brand">STEP 2 — CALL USCCA</div><button class="btn" onclick="location.href=\'tel:'+USCCA_PHONE">CALL USCCA ('+USCCA_DISPLAY+')</button></section>'; if(shoot){html+='<section class="panel"><div class="brand">STEP 3 — CONTACT FAMILY</div><h2>'+(contact.name||'No contact saved')+'</h2><p class="text">'+(contact.phone||'')+'</p>'+(contact.phone?'<button class="btn" onclick="location.href=\'tel:'+contact.phone.replace(/[^0-9+]/g,\'\')">CALL CONTACT</button>':'')+'<div class="script">“I’ve been involved in a defensive incident. I’m safe. Do not discuss anything with anyone until I have legal guidance.”</div></section>'} html+='</div>'; el(html)}
function renderAftermath(){el('<div class="shell"><button class="btn dark" onclick="renderHome()">Exit</button><div class="brand">PRIME DEFENSE PROTECTION MEMBER</div><h1 class="title">Aftermath Mode</h1><section class="panel"><div class="brand">WHEN POLICE ARRIVE</div><ul class="text"><li>Keep your hands visible.</li><li>Follow commands immediately.</li><li>Do not make sudden movements.</li></ul></section><section class="panel"><div class="brand">STATEMENT CONTROL</div><ul class="text"><li>Keep statements brief and factual.</li><li>Do not speculate or fill silence.</li><li>Wait for legal guidance before detailed statements.</li></ul></section><div class="warn">You may not remember everything clearly right now. That is normal.</div></div>')}
boot();
</script></body></html>`;
app.get('/', (req,res)=>res.send(html));
app.use((req,res)=>res.send(html));
app.listen(PORT, ()=>console.log('Prime Defense single-service app running on port '+PORT));
